KTB-15
Artur-star/KotlinTelegramBot pull request #12
Opened 2024-08-19 14:32 UTC by Artur-star

2024-08-19 14:33 UTC, Artur-star commented
Не могу разобраться с кодировкой
![image](https://github.com/user-attachments/assets/c03613d9-1588-47ff-aba7-f43186ed0005)

2024-08-20 18:22 UTC, kaznikit requested changes

2024-08-20 18:22 UTC, kaznikit commented on src/main/kotlin/TelegramBotService.kt
> +        val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$encodedText"
давай хост https://api.telegram.org вынесем в константу

2024-08-20 18:27 UTC, kaznikit commented
> Не могу разобраться с кодировкой ![image](https://private-user-images.githubusercontent.com/55159022/359139629-c03613d9-1588-47ff-aba7-f43186ed0005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzg0MjQsIm5iZiI6MTcyNDE3ODEyNCwicGF0aCI6Ii81NTE1OTAyMi8zNTkxMzk2MjktYzAzNjEzZDktMTU4OC00N2ZmLWFiYTctZjQzMTg2ZWQwMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2RiYTE4NTM5Y2MzM2UzNzBlMzNmZGRkODFkODE5MDEzZDVlYWUyY2U2ODkzYzM0MGFmNzczY2FlYjk3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7PVxp5_riQuz7EvpxhcjPuAwwJoaOQpH3032NHMNxE)

такой способ пробовал? также можно попробовать в idea изменить encoding на utf-8
```
val encoded = URLEncoder.encode(message, StandardCharsets.UTF_8)
val urlSendMessage = "$API_BOT$botToken/sendMessage?chat_id=$chatId&text=$encoded"
```

2024-08-22 15:03 UTC, Artur-star commented
> > Не могу разобраться с кодировкой ![image](https://private-user-images.githubusercontent.com/55159022/359139629-c03613d9-1588-47ff-aba7-f43186ed0005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzg0MjQsIm5iZiI6MTcyNDE3ODEyNCwicGF0aCI6Ii81NTE1OTAyMi8zNTkxMzk2MjktYzAzNjEzZDktMTU4OC00N2ZmLWFiYTctZjQzMTg2ZWQwMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2RiYTE4NTM5Y2MzM2UzNzBlMzNmZGRkODFkODE5MDEzZDVlYWUyY2U2ODkzYzM0MGFmNzczY2FlYjk3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7PVxp5_riQuz7EvpxhcjPuAwwJoaOQpH3032NHMNxE)
> 
> такой способ пробовал? также можно попробовать в idea изменить encoding на utf-8
> 
> ```
> val encoded = URLEncoder.encode(message, StandardCharsets.UTF_8)
> val urlSendMessage = "$API_BOT$botToken/sendMessage?chat_id=$chatId&text=$encoded"
> ```
А в каком месте в идее? 
![image](https://github.com/user-attachments/assets/5f678054-491e-4438-ba17-19d8b2fba942)
![image](https://github.com/user-attachments/assets/57c6a791-c796-4dfa-ab97-98978bf6dec5)

2024-08-22 15:04 UTC, Artur-star commented
> > > Не могу разобраться с кодировкой ![image](https://private-user-images.githubusercontent.com/55159022/359139629-c03613d9-1588-47ff-aba7-f43186ed0005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzg0MjQsIm5iZiI6MTcyNDE3ODEyNCwicGF0aCI6Ii81NTE1OTAyMi8zNTkxMzk2MjktYzAzNjEzZDktMTU4OC00N2ZmLWFiYTctZjQzMTg2ZWQwMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2RiYTE4NTM5Y2MzM2UzNzBlMzNmZGRkODFkODE5MDEzZDVlYWUyY2U2ODkzYzM0MGFmNzczY2FlYjk3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7PVxp5_riQuz7EvpxhcjPuAwwJoaOQpH3032NHMNxE)
> > 
> > 
> > такой способ пробовал? также можно попробовать в idea изменить encoding на utf-8
> > ```
> > val encoded = URLEncoder.encode(message, StandardCharsets.UTF_8)
> > val urlSendMessage = "$API_BOT$botToken/sendMessage?chat_id=$chatId&text=$encoded"
> > ```
> 
> А в каком месте в идее? ![image](https://private-user-images.githubusercontent.com/55159022/360522186-5f678054-491e-4438-ba17-19d8b2fba942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTAsIm5iZiI6MTcyNDMzODk5MCwicGF0aCI6Ii81NTE1OTAyMi8zNjA1MjIxODYtNWY2NzgwNTQtNDkxZS00NDM4LWJhMTctMTlkOGIyZmJhOTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZGMwN2Q2ODI4NzgxMWQzOWRiMDc5ZGVhZTM3YTc1YTYyZjJiMDUwYjkwZDkwNzNhNzEzZDlmMDdlNjFkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-oO1fsdnU2sUSKZGAsdKPTYh_i_uh46AsPD64nuIucs) ![image](https://private-user-images.githubusercontent.com/55159022/360522590-57c6a791-c796-4dfa-ab97-98978bf6dec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTAsIm5iZiI6MTcyNDMzODk5MCwicGF0aCI6Ii81NTE1OTAyMi8zNjA1MjI1OTAtNTdjNmE3OTEtYzc5Ni00ZGZhLWFiOTctOTg5NzhiZjZkZWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODM0N2FhYWI5ZjBjZTA3YzUzODQ2ODk5ZGU3Y2M3NzdkZDk1MGFkOWIwZjdkYWFhMGIwNmE0OGM5MWVjZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpVsRHfKv_nDUuT0bRQjP0bXw_viNPaV46Dod3JZ8ik)

Первый способ в методе указан, не работает

2024-08-22 16:43 UTC, kaznikit commented
> > > > Не могу разобраться с кодировкой ![image](https://private-user-images.githubusercontent.com/55159022/359139629-c03613d9-1588-47ff-aba7-f43186ed0005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzg0MjQsIm5iZiI6MTcyNDE3ODEyNCwicGF0aCI6Ii81NTE1OTAyMi8zNTkxMzk2MjktYzAzNjEzZDktMTU4OC00N2ZmLWFiYTctZjQzMTg2ZWQwMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2RiYTE4NTM5Y2MzM2UzNzBlMzNmZGRkODFkODE5MDEzZDVlYWUyY2U2ODkzYzM0MGFmNzczY2FlYjk3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7PVxp5_riQuz7EvpxhcjPuAwwJoaOQpH3032NHMNxE)
> > > 
> > > 
> > > такой способ пробовал? также можно попробовать в idea изменить encoding на utf-8
> > > ```
> > > val encoded = URLEncoder.encode(message, StandardCharsets.UTF_8)
> > > val urlSendMessage = "$API_BOT$botToken/sendMessage?chat_id=$chatId&text=$encoded"
> > > ```
> > 
> > 
> > А в каком месте в идее? ![image](https://private-user-images.githubusercontent.com/55159022/360522186-5f678054-491e-4438-ba17-19d8b2fba942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTAsIm5iZiI6MTcyNDMzODk5MCwicGF0aCI6Ii81NTE1OTAyMi8zNjA1MjIxODYtNWY2NzgwNTQtNDkxZS00NDM4LWJhMTctMTlkOGIyZmJhOTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZGMwN2Q2ODI4NzgxMWQzOWRiMDc5ZGVhZTM3YTc1YTYyZjJiMDUwYjkwZDkwNzNhNzEzZDlmMDdlNjFkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-oO1fsdnU2sUSKZGAsdKPTYh_i_uh46AsPD64nuIucs) ![image](https://private-user-images.githubusercontent.com/55159022/360522590-57c6a791-c796-4dfa-ab97-98978bf6dec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTAsIm5iZiI6MTcyNDMzODk5MCwicGF0aCI6Ii81NTE1OTAyMi8zNjA1MjI1OTAtNTdjNmE3OTEtYzc5Ni00ZGZhLWFiOTctOTg5NzhiZjZkZWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODM0N2FhYWI5ZjBjZTA3YzUzODQ2ODk5ZGU3Y2M3NzdkZDk1MGFkOWIwZjdkYWFhMGIwNmE0OGM5MWVjZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpVsRHfKv_nDUuT0bRQjP0bXw_viNPaV46Dod3JZ8ik)
> 
> Первый способ в методе указан, не работает

можешь попробовать еще здесь посмотреть. если не поможет давай пока заменим на англ версию, буду дальше разбираться и вернусь к тебе с ответом. пока здесь аппрув тогда
<img width="986" alt="Снимок экрана 2024-08-22 в 19 40 28" src="https://github.com/user-attachments/assets/321d85ba-fa46-42eb-8512-dfe439054889">

2024-08-22 16:44 UTC, kaznikit approved these changes

2024-08-23 03:26 UTC, Artur-star commented
> > > > > Не могу разобраться с кодировкой ![image](https://private-user-images.githubusercontent.com/55159022/359139629-c03613d9-1588-47ff-aba7-f43186ed0005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzg0MjQsIm5iZiI6MTcyNDE3ODEyNCwicGF0aCI6Ii81NTE1OTAyMi8zNTkxMzk2MjktYzAzNjEzZDktMTU4OC00N2ZmLWFiYTctZjQzMTg2ZWQwMDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE4MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2RiYTE4NTM5Y2MzM2UzNzBlMzNmZGRkODFkODE5MDEzZDVlYWUyY2U2ODkzYzM0MGFmNzczY2FlYjk3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7PVxp5_riQuz7EvpxhcjPuAwwJoaOQpH3032NHMNxE)
> > > > 
> > > > 
> > > > такой способ пробовал? также можно попробовать в idea изменить encoding на utf-8
> > > > ```
> > > > val encoded = URLEncoder.encode(message, StandardCharsets.UTF_8)
> > > > val urlSendMessage = "$API_BOT$botToken/sendMessage?chat_id=$chatId&text=$encoded"
> > > > ```
> > > 
> > > 
> > > А в каком месте в идее? ![image](https://private-user-images.githubusercontent.com/55159022/360522186-5f678054-491e-4438-ba17-19d8b2fba942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTAsIm5iZiI6MTcyNDMzODk5MCwicGF0aCI6Ii81NTE1OTAyMi8zNjA1MjIxODYtNWY2NzgwNTQtNDkxZS00NDM4LWJhMTctMTlkOGIyZmJhOTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZGMwN2Q2ODI4NzgxMWQzOWRiMDc5ZGVhZTM3YTc1YTYyZjJiMDUwYjkwZDkwNzNhNzEzZDlmMDdlNjFkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-oO1fsdnU2sUSKZGAsdKPTYh_i_uh46AsPD64nuIucs) ![image](https://private-user-images.githubusercontent.com/55159022/360522590-57c6a791-c796-4dfa-ab97-98978bf6dec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTAsIm5iZiI6MTcyNDMzODk5MCwicGF0aCI6Ii81NTE1OTAyMi8zNjA1MjI1OTAtNTdjNmE3OTEtYzc5Ni00ZGZhLWFiOTctOTg5NzhiZjZkZWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODM0N2FhYWI5ZjBjZTA3YzUzODQ2ODk5ZGU3Y2M3NzdkZDk1MGFkOWIwZjdkYWFhMGIwNmE0OGM5MWVjZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpVsRHfKv_nDUuT0bRQjP0bXw_viNPaV46Dod3JZ8ik)
> > 
> > 
> > Первый способ в методе указан, не работает
> 
> можешь попробовать еще здесь посмотреть. если не поможет давай пока заменим на англ версию, буду дальше разбираться и вернусь к тебе с ответом. пока здесь аппрув тогда <img alt="Снимок экрана 2024-08-22 в 19 40 28" width="986" src="https://private-user-images.githubusercontent.com/20563332/360555705-321d85ba-fa46-42eb-8512-dfe439054889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODM1NzksIm5iZiI6MTcyNDM4MzI3OSwicGF0aCI6Ii8yMDU2MzMzMi8zNjA1NTU3MDUtMzIxZDg1YmEtZmE0Ni00MmViLTg1MTItZGZlNDM5MDU0ODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMjExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDkwNzkyOTAxZjdjMWQ2ZTFiMGM2NGU4Y2NjY2YzNTk1ZjA2NTkxZmE5YWM0YjdlMGU4YTQ2MzYzNjFlOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9P68gvCm-GshDdK-BWpVPCqLjgggAecCgFMNoM3-I0s">
Так по умолчанию стоит

2024-08-23 03:26 UTC, merged