KTB-10 test functionality
Artur-star/KotlinTelegramBot pull request #8
Opened 2024-08-12 14:16 UTC by Artur-star

2024-08-13 03:09 UTC, kaznikit requested changes

2024-08-13 03:09 UTC, kaznikit commented on src/main/kotlin/LearnWordsTrainer.kt
> +        } else {
ощущение что код немного поехал, так как не вижу закрывающей скобки от else) попробуй сделать автоформатирование

2024-08-13 03:52 UTC, Artur-star commented on src/main/kotlin/LearnWordsTrainer.kt
> +        } else {
Сделал автоформатирование, все также осталось, в idea все красиво выглядит, видимо в гитхаб код съезжает, закрывающая скобка стоит перед shuffled()

2024-08-14 06:49 UTC, kaznikit approved these changes

2024-08-14 13:31 UTC, merged